export const RESOURCES = {
  gold: "Золота",
  silver: "Срібла",
  tokens: "Токен",
  tanks: "Танка",
  red_tokens: "Червоний Токен",
  drawings: "Креслення",
  premium_akk: "Преміум аккаунт",
};

export const TANKS = {
  2: {
    id: 2,
    name: "Об'єкт 490",
    transcription: "obj_490",
    type: "ht",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/obj_490.html",
    exchange: 7600,
  },
  3: {
    id: 3,
    name: "Об'єкт 490 Білка",
    transcription: "obj_490_squirrel",
    type: "camo",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/obj_490.html",
    exchange: 1500,
  },
  5: {
    id: 5,
    name: "PZ 5/4",
    transcription: "pz_5-4",
    type: "lt",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/pz_5-4.html",
    exchange: 5600,
  },
  6: {
    id: 6,
    name: "Т-20-22",
    transcription: "t_20_22",
    type: "lt",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/t-20-22.html",
    exchange: 6800,
  },
  7: {
    id: 7,
    name: "Sheridan",
    transcription: "sheridan",
    type: "lt",
    land: "usa",
    link: "https://lonja971.github.io/WomT_wiki/tanks/usa/sheridan.html",
    exchange: 7200,
  },
  8: {
    id: 8,
    name: "БТ-СВ",
    transcription: "bt_sv",
    type: "lt",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ussr/bt-sv.html",
    exchange: 7000,
  },
  9: {
    id: 9,
    name: "AMX ELS bic",
    transcription: "amx_els_bic",
    type: "lt",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/amx_els_bis.html",
    exchange: 6400,
  },
  10: {
    id: 10,
    name: "ELS EVEN 90",
    transcription: "els_even_90",
    type: "lt",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/els_even_90.html",
    exchange: 6800,
  },
  11: {
    id: 11,
    name: "Progetto 46",
    transcription: "progetto_46",
    type: "lt",
    land: "it",
    link: "https://lonja971.github.io/WomT_wiki/tanks/italy/progetto_46.html",
    exchange: 6800,
  },
  12: {
    id: 12,
    name: "Т-34 Харків",
    transcription: "t_34_kharkiv",
    type: "lt",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/t34_kharkiv.html",
    exchange: 6400,
  },
  13: {
    id: 13,
    name: "Т-54",
    transcription: "t_54",
    type: "lt",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/t54.html",
    exchange: 6800,
  },
  14: {
    id: 14,
    name: "Kranwagn",
    transcription: "kranwagn",
    type: "ht",
    land: "sw",
    link: "https://lonja971.github.io/WomT_wiki/tanks/sweden/kranwagn.html",
    exchange: 7600,
  },
  15: {
    id: 15,
    name: "AMX M4 54",
    transcription: "amx_m4_54",
    type: "ht",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/amx_m4_54.html",
    exchange: 7200,
  },
  16: {
    id: 16,
    name: "Maus",
    transcription: "maus",
    type: "ht",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/maus.html",
    exchange: 7600,
  },
  17: {
    id: 17,
    name: "Tiger (P)",
    transcription: "tiger_p",
    type: "ht",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/tiger_p.html",
    exchange: 6800,
  },
  18: {
    id: 18,
    name: "Tiger Titan",
    transcription: "tiger_titan",
    type: "ht",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/tiger_titan.html",
    exchange: 6800,
  },
  19: {
    id: 19,
    name: "M5 Yoh",
    transcription: "m5_yoh",
    type: "ht",
    land: "usa",
    link: "https://lonja971.github.io/WomT_wiki/tanks/usa/m5_yoh.html",
    exchange: 7600,
  },
  20: {
    id: 20,
    name: "Bisonte C45",
    transcription: "bisonte_c45",
    type: "ht",
    land: "it",
    link: "https://lonja971.github.io/WomT_wiki/tanks/italy/bisonte_c45.html",
    exchange: 7200,
  },
  21: {
    id: 21,
    name: "Type 5 Heavy",
    transcription: "type_5_heavy",
    type: "ht",
    land: "jp",
    link: "https://lonja971.github.io/WomT_wiki/tanks/japan/type_5_heavy.html",
    exchange: 7600,
  },
  22: {
    id: 22,
    name: "Т-64 БМ Оплот",
    transcription: "t_64_bm_oplot",
    type: "ht",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/t640plot.html",
    exchange: 7600,
  },
  23: {
    id: 23,
    name: "КВ-2",
    transcription: "kv_2",
    type: "ht",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ussr/kv-2.html",
    exchange: 6400,
  },
  24: {
    id: 24,
    name: "ИС-2 Варіант ||",
    transcription: "is_2_var2",
    type: "ht",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ussr/is-2_var_2.html",
    exchange: 6800,
  },
  25: {
    id: 25,
    name: "T-95",
    transcription: "t_95",
    type: "td",
    land: "usa",
    link: "https://lonja971.github.io/WomT_wiki/tanks/usa/t-95.html",
    exchange: 7200,
  },
  26: {
    id: 26,
    name: "Grill 15",
    transcription: "grill_15",
    type: "td",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/grill_15.html",
    exchange: 7600,
  },
  27: {
    id: 27,
    name: "Віндікатор",
    transcription: "vindicator",
    type: "td",
    land: "inter",
    link: "https://lonja971.github.io/WomT_wiki/tanks/vindicator.html",
    exchange: 6800,
  },
  28: {
    id: 28,
    name: "Minotauro",
    transcription: "minotauro",
    type: "td",
    land: "it",
    link: "https://lonja971.github.io/WomT_wiki/tanks/italy/minotauro.html",
    exchange: 7600,
  },
  29: {
    id: 29,
    name: "Bat-Chat 25t",
    transcription: "bat_chat_25t",
    type: "lt",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/bat-chat_25t.html",
    exchange: 6400,
  },
  30: {
    id: 30,
    name: "T-57 Heavy",
    transcription: "t_57_heavy",
    type: "ht",
    land: "usa",
    link: "https://lonja971.github.io/WomT_wiki/tanks/usa/t57_heavy.html",
    exchange: 7200,
  },
  31: {
    id: 31,
    name: "Togg ||*",
    transcription: "togg_2",
    type: "ht",
    land: "br",
    link: "https://lonja971.github.io/WomT_wiki/tanks/britaine/togg_2.html",
    exchange: 6400,
  },
  32: {
    id: 32,
    name: "ИС-7",
    transcription: "is_7",
    type: "ht",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ussr/is-7.html",
    exchange: 7600,
  },
  33: {
    id: 33,
    name: "Дробар",
    transcription: "crusher",
    type: "ht",
    land: "inter",
    link: "https://lonja971.github.io/WomT_wiki/tanks/krushitel.html",
    exchange: 6800,
  },
  34: {
    id: 34,
    name: "СУ-152",
    transcription: "sy_152",
    type: "td",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ussr/sy-152.html",
    exchange: 6000,
  },
  35: {
    id: 35,
    name: "S 35 CA",
    transcription: "s_35_ca",
    type: "td",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/s_35_ca.html",
    exchange: 5600,
  },
  36: {
    id: 36,
    name: "Cherchill GC",
    transcription: "cherchill_gc",
    type: "td",
    land: "br",
    link: "https://lonja971.github.io/WomT_wiki/tanks/britaine/churchill_gc.html",
    exchange: 5600,
  },
  37: {
    id: 37,
    name: "AMX 30 1-prot",
    transcription: "amx_30_1prot",
    type: "lt",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/amx_30-1.html",
    exchange: 6800,
  },
  38: {
    id: 38,
    name: "PZ B2",
    transcription: "pz_b2",
    type: "ht",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/pz_b2.html",
    exchange: 6400,
  },
  39: {
    id: 39,
    name: "WZ 111",
    transcription: "wz_111",
    type: "ht",
    land: "ch",
    link: "https://lonja971.github.io/WomT_wiki/tanks/china/wz_111.html",
    exchange: 6400,
  },
  40: {
    id: 40,
    name: "СУ-130 ПМ",
    transcription: "sy_130_pm",
    type: "td",
    land: "ussr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ussr/sy-130pm.html",
    exchange: 6800,
  },
  41: {
    id: 41,
    name: "Strv 103b",
    transcription: "strv_103b",
    type: "td",
    land: "sw",
    link: "https://lonja971.github.io/WomT_wiki/tanks/sweden/strv_103b.html",
    exchange: 7600,
  },
  42: {
    id: 42,
    name: "Turbo Räumpanzer",
    smallName: "Turbo Räump...",
    transcription: "turbo_raumpanzer",
    type: "ht",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/turbo_raumpanzer.html",
    exchange: 6800,
  },
  43: {
    id: 43,
    name: "Шерідан Ракетний",
    transcription: "sheridan_rocket",
    type: "camo",
    land: "usa",
    link: "https://lonja971.github.io/WomT_wiki/tanks/usa/sheridan.html",
    exchange: 1500,
  },
  44: {
    id: 44,
    name: "ELS EVEN 90 Мандарин",
    transcription: "els_even_90_tangerine",
    type: "camo",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/els_even_90.html",
    exchange: 1500,
  },
  45: {
    id: 45,
    name: "Т-34 Харків Зимній снайпер",
    transcription: "t_34_kharkiv_winter",
    type: "camo",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/t34_kharkiv.html",
    exchange: 2000,
  },
  46: {
    id: 46,
    name: "Т-54 Патріот1",
    transcription: "t_54_patriot1",
    type: "camo",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/t54.html",
    exchange: 500,
  },
  47: {
    id: 47,
    name: "Т-54 Патріот2",
    transcription: "t_54_patriot2",
    type: "camo",
    land: "ua",
    link: "https://lonja971.github.io/WomT_wiki/tanks/ukraine/t54.html",
    exchange: 500,
  },
  48: {
    id: 48,
    name: "AMX M4 54 Новорічний",
    transcription: "amx_m4_54_newyear",
    type: "camo",
    land: "fr",
    link: "https://lonja971.github.io/WomT_wiki/tanks/france/amx_m4_54.html",
    exchange: 2000,
  },
  49: {
    id: 49,
    name: "Maus Легіонер",
    transcription: "maus_legionary",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/maus.html",
    exchange: 1500,
  },
  50: {
    id: 50,
    name: "Maus Привид",
    transcription: "maus_ghost",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/maus.html",
    exchange: 2000,
  },
  51: {
    id: 51,
    name: "Золотий Тигр",
    transcription: "golden_tiger",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/white_tiger.html",
    exchange: 2000,
  },
  52: {
    id: 52,
    name: `Тигр "Чорний Ліс"`,
    transcription: "tiger_blackforest",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/white_tiger.html",
    exchange: 1500,
  },
  53: {
    id: 53,
    name: "Tiger (P) GT",
    transcription: "tiger_p_gt",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/tiger_p.html",
    exchange: 1500,
  },
  54: {
    id: 54,
    name: "T-95 Незламний",
    transcription: "t_95_unbreakable",
    type: "camo",
    land: "usa",
    link: "https://lonja971.github.io/WomT_wiki/tanks/usa/t-95.html",
    exchange: 1500,
  },
  55: {
    id: 55,
    name: "Grill 15 Новорічний Рейдер",
    transcription: "grill_15_newyear_raider",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/grill_15.html",
    exchange: 2500,
  },
  56: {
    id: 56,
    name: `Віндікатор "Темні янголи"`,
    transcription: "vindicator_dark_angels",
    type: "camo",
    land: "inter",
    link: "https://lonja971.github.io/WomT_wiki/tanks/vindicator.html",
    exchange: 1500,
  },
  57: {
    id: 57,
    name: `Віндікатор "Імперський кулак"`,
    transcription: "vindicator_imperial_fist",
    type: "camo",
    land: "inter",
    link: "https://lonja971.github.io/WomT_wiki/tanks/vindicator.html",
    exchange: 1500,
  },
  58: {
    id: 58,
    name: "Minotauro Новорічний",
    transcription: "minotauro_newyear",
    type: "camo",
    land: "it",
    link: "https://lonja971.github.io/WomT_wiki/tanks/italy/minotauro.html",
    exchange: 1500,
  },
  59: {
    id: 59,
    name: `Waf. Auf E 100`,
    transcription: "waff_auf_e_100",
    type: "td",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/waf_auf_e100.html",
    exchange: 7500,
  },
  60: {
    id: 60,
    name: "Останній Ваффентраген",
    transcription: "waff_auf_e_100_the_last",
    type: "camo",
    land: "ge",
    link: "https://lonja971.github.io/WomT_wiki/tanks/germany/waf_auf_e100.html",
    exchange: 2500,
    bg: "waff_auf_e_100_the_last-bg",
  },
};

//---EXCHANGE---

export const EXCHANGE = {
  gold: {
    silver: {
      exchange: "silver",
      exchangeValue: "2500",
      getValue: "100",
    },
    tanks: {
      exchange: "tanks",
      exchangeValue: "10",
      getValue: "100",
    },
    premium_akk: {
      exchange: "premium_akk",
      exchangeValue: "5",
      getValue: "500",
    },
    drawings: {
      exchange: "drawings",
      exchangeValue: "1",
      getValue: "600",
    },
    tokens: {
      exchange: "tokens",
      exchangeValue: "1",
      getValue: "100",
    },
    red_tokens: {
      exchange: "red_tokens",
      exchangeValue: "1",
      getValue: "200",
    },
    tanks: {}
  },
  red_tokens: {
    tokens: {
      exchange: "tokens",
      exchangeValue: "2",
      getValue: "1",
    },
    gold: {
      exchange: "gold",
      exchangeValue: "400",
      getValue: "1",
    },
  }
};

//---CASES---

export const CASES = {
  main_cases: {
    name: "Main Кейс",
    transcription: "main_case",
    animation: "default",
  },
  regular_cases: {
    name: "Звичайний Кейс",
    transcription: "regular_case",
    animation: "regular_cases",
  },
  special_cases: {
    name: "Особливий Кейс",
    transcription: "special_case",
    animation: "special_cases",
  },
  rare_cases: {
    name: "Рідкісний Кейс",
    transcription: "rare_case",
    animation: "rare_cases",
  },
  mythical_cases: {
    name: "Міфічний Кейс",
    transcription: "mythical_case",
    animation: "mythical_cases",
  },
  legendary_cases: {
    name: "Легендарний Кейс",
    transcription: "legendary_case",
    animation: "legendary_cases",
  },
  waff_cases: {
    name: "Останній Ваффентрагер",
    transcription: "waff_case",
    animation: "waff_case",
  },
};

//---CASES-RESOURCES-INFO---

export const MAIN_CASE = [
  { 
    probability: 100,
    items: [
      { type: "case", name: "regular_cases", probability: 40, amounts: [1] },
      { type: "case", name: "special_cases", probability: 32, amounts: [1] },
      { type: "case", name: "rare_cases", probability: 18, amounts: [1] },
      { type: "case", name: "mythical_cases", probability: 7, amounts: [1] },
      { type: "case", name: "legendary_cases", probability: 3, amounts: [1] },
    ]
  },
  { type: "gold", probability: 15, amounts: [ 200, 300, 500 ] },
  { type: "red_tokens", probability: 15, amounts: [ 1, 2 ] },
];

export const REGULAR_CASE = [
  { type: "silver", probability: 40, amounts: [1000, 1500], default: true },
  { type: "tanks", probability: 40, amounts: [2, 3] },
  { type: "gold", probability: 20, amounts: [100] },
];

export const SPECIAL_CASE = [
  { type: "silver", probability: 30, amounts: [2000], default: true },
  { type: "tanks", probability: 20, amounts: [5] },
  { type: "premium_akk", probability: 20, amounts: [1] },
  { type: "gold", probability: 20, amounts: [ 300, 500 ] },
  //{ type: "skin", probability: 10, amounts: 1 },
];

export const RARE_CASE = [
  { type: "silver", probability: 30, amounts: [ 3000, 5000 ], default: true },
  { type: "premium_akk", probability: 35, amounts: [1] },
  { type: "gold", probability: 30, amounts: [ 500, 700 ] },
  { type: "red_tokens", probability: 10, amounts: [ 1, 2 ] },
  { type: "drawings", probability: 10, amounts: [1] },
];

export const MYTHICAL_CASE = [
  { type: "premium_akk", probability: 35, amounts: [2] },
  { type: "gold", probability: 30, amounts: [1000, 2000] },
  { type: "drawings", probability: 30, amounts: [1], default: true },
  { type: "red_tokens", probability: 10, amounts: [2] },
  { type: "tank", id: "3", probability: 20, amounts: [1] }, // 20% на всі скіни
];

export const LEGENDARY_CASE = [
  { type: "gold", probability: 30, amounts: [2000, 3000] },
  { type: "drawings", probability: 25, amounts: [2], default: true, dafaultAmount: 2, },
  { type: "red_tokens", probability: 25, amounts: [2, 6] },
  { type: "tank", id: "42", probability: 20, amounts: [1] },
  { type: "tank", id: "2", probability: 20, amounts: [1] },
];

export const WAFF_CASE = [
  { type: "gold", probability: 10, amounts: [2000, 3000], default: true },
  { type: "tank", id: "59", probability: 100, amounts: [1] },
  { type: "tank", id: "60", probability: 100, amounts: [1] },
];
